### PR TITLE
Singleton: Do not require sync package

### PR DESCRIPTION
**Pull request by leonklingele**

### CODE REVIEW

**Comment by leonklingele** [comment]
IMO it is better not to rely on the sync package in this case, what do you think?

**Comment by tmrts** [comment]
@leonklingele you'd still have to use mutual exclusion locks to prevent obscure race condition bugs (in modern computers there isn't partial reference updates, so your code is okay, but it should be explicit), plus `once.Do(...)` reads like a poem :smile: 

Is there a reason why we shouldn't rely on `sync`? if so, we should reconsider

**Comment by leonklingele** [comment]
> still have to use mutual exclusion locks

Oops, you're right!

> Is there a reason why we shouldn't rely on `sync`?

Well, it does add some overhead, but it's definitely better to circumvent race conditions in the example.

Sorry!

**Comment by tmrts** [comment]
@leonklingele no problem at all :smile: 

My litmus test for patterns in this repository is that it should be **readable** and it should be **as simple as possible, but no simpler**. Optimization comes after those

**Pull request closed without merging**
