### PR TITLE
Update builder.md

### PR DESCRIPTION
**Pull request by coreydaley**

### CODE REVIEW

**Comment by sluongng** [comment]
@coreydaley Do you happen to know how exactly should I use `NewBuilder()` in `assembly := car.NewBuilder().Paint(car.RedColor)` ?

**Comment by coreydaley** [comment]
@sluongng 
There are really two ways to use it (given that this is an incomplete example):

NewBuilder could be a function that returns a Builder, meaning that what you return must implement the Builder interface.

You could change it to be:
NewBuilder could be a struct that contains the correct fields and functions to adhere to the Builder interface, in which case your code would look more like:
assembly := car.NewBuilder{}
assembly.Paint(car.RedColor)

**Comment by sluongng** [comment]
could you please include code snippet of what you just explained in the PR?

I would love to read in detail and I think others might have same question as I did.

**Comment by coreydaley** [comment]
@sluongng 
https://github.com/coreydaley/builderExample

go get github.com/coreydaley/builderExample

**Comment by crossgit** [comment]
@sluongng @coreydaley 
May I look at this code? https://github.com/coreydaley/builderExample
Where can I see this?

**Comment by coreydaley** [comment]
@crossgit that repo was deleted long ago

**Pull request closed without merging**
